#!/bin/sh

ARG=$1

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 [brute|basic|optimal]"
	exit 1
fi

javac ReadFile.java Points.java OrderedPair.java

ARG=$1

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 [brute|basic|optimal]"
	exit 1
fi

java ReadFile $ARG
